### PR TITLE
Moved from crop to extent for filling images

### LINKED ISSUE #32: Diff failing on Windows
On Windows 7 and Windows server 2012, the code didn't work as expected. Even when two completely different files were passed, the diff returned success. On digging further, noticed that the crop function called on gm always produced a one by one pixel file.
this.crop(params.toWidth, params.toHeight, 0, 0);

After using gm without imagemagick, (so using graphicsmagick instead) the code succeeded.

Any ideas about this?

If we have the option to use imagemagick or graphicsmagick from this module, that will solve the problem.

### PR DESCRIPTION
**Pull request by twolfson**
In #32, we received a report of 2 images failing to properly compare. We resolved that the issue was due to us improperly using `crop` which lead to 1 error and 1 of the images had a poor encoding. The combination of these 2 lead `gm` to create 1x1 images to diff.

Reference images here: https://github.com/uber/image-diff/pull/33#issuecomment-196530515

To remedy this, we are moving off of the improper command `crop` (which truncates images) to the more accurate `extent` (which extends images). In this PR:

- Added test to verify we preserve transparent backgrounds
- Moved from `crop` to `extent`
- Stopped writing to damn `gm` prototype, even if we subclass it
- Updated CHANGELOG
- Fixes #32, closes #33 

For the release verison, please release as `1.4.0`:

```bash
./release.sh 1.4.0
```

/cc @mlmorg

### CODE REVIEW

File: lib/image-diff.js [hunk 1]
```diff
@@ -8,25 +9,25 @@ var mkdirp = require('mkdirp');
...
 
 // Define custom resize function
-// Taken from https://github.com/twolfson/twolfson.com/blob/3.4.0/test/perceptual-tests/twolfson.com_test.js#L88-L107
-// TODO: Make image resizing its own library
-// DEV: This does not pollute gm.prototype
-gm.prototype.fillFromTo = function (params) {
+function transparentExtent(gm, params) {
+  // Assert we received our parameters
+  assert.notEqual(params.width, undefined);
+  assert.notEqual(params.height, undefined);
```
Comment (Qix-) [inline lib/image-diff.js]: Why not more readable error messages? These parameters are read in using input from the user (eventually) so there's a chance the consuming code could have erroneous input. An assert doesn't really explain the issue all that well.

Comment (twolfson) [inline lib/image-diff.js]: These assertions are for preventing typos from developers. There's not really a case where the error would come from user error:

- If the file doesn't exist, then we will get an `ENOENT` error during the earlier `fs.stat`/`fs.exists` call and we won't be upscaling the image
    - https://github.com/uber/image-diff/blob/1.3.0/lib/image-diff.js#L122-L128
    - https://github.com/uber/image-diff/blob/1.3.0/lib/image-diff.js#L132
    - https://github.com/uber/image-diff/blob/1.3.0/lib/image-diff.js#L33-L52
    - https://github.com/uber/image-diff/blob/1.3.0/lib/image-diff.js#L137
    - https://github.com/uber/image-diff/blob/1.3.0/lib/image-diff.js#L170-L173
- Otherwise, we will always be receiving `height`/`width` from `gm.size` so if those don't exist, then we have a deeper problem in `gm` itself

File: lib/image-diff.js [hunk 2]
```diff
@@ -8,25 +9,25 @@ var mkdirp = require('mkdirp');
...
   // Fill in new space with white background
   // TODO: Parameterize background color (should be considered 'transparent' color in this case)
-  this.borderColor('transparent');
-  this.border(Math.max(params.toWidth - params.fromWidth, 0), Math.max(params.toHeight - params.fromHeight, 0));
+  gm.background('transparent');
 
   // Anchor image to upper-left
   // TODO: Parameterize anchor point
-  this.gravity('SouthEast');
+  gm.gravity('NorthWest');
```
Comment (x3au) [inline lib/image-diff.js]: Isn't NorthWest the default value, so we may not have to set it explicitly?

Comment (twolfson) [inline lib/image-diff.js]: Yea, it's the default but I prefer to be explicit and we could parameterize it easily. For example, in the following images, what if someone wanted the smaller one to move to the lower right when upscaled?

https://github.com/uber/image-diff/blob/1.3.0/test/test-files/checkerboard.png

https://github.com/uber/image-diff/blob/1.3.0/test/test-files/checkerboard-excess.png

Note: Currently for gravity, it will make the 2 images look the same except there will be a transparent edge for the smaller one

File: lib/image-diff.js (hunk 1 above)
Comment (Qix-) [inline lib/image-diff.js]: :+1: gotcha

File: lib/image-diff.js (hunk 2 above)
Comment (x3au) [inline lib/image-diff.js]: Cool!

**Comment by x3au** [comment]
Thanks for the fix!
